[package]
name = "tauri-plugin-android-account"
version = "0.1.0"
authors = [ "xStack" ]
description = ""
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-android-account"

[dependencies]
tauri = { version = "2.11.3" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2.6.3", features = ["build"] }
